apiVersion: v2
name: account-operator
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: account-operator-crds
    condition: crds.enabled
